// +build !noasm !appengine
// Code generated by asm2asm, DO NOT EDIT.

package base64x

import (
	`github.com/bytedance/sonic/loader`
)

const (
    _entry__b64decode = 1584
    _entry__b64encode = 256
)

const (
    _stack__b64decode = 120
    _stack__b64encode = 40
)

const (
    _size__b64decode = 13920
    _size__b64encode = 864
)

var (
    _pcsp__b64decode = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {12, 40},
        {13, 48},
        {10428, 120},
        {10432, 48},
        {10433, 40},
        {10435, 32},
        {10437, 24},
        {10439, 16},
        {10441, 8},
        {10445, 0},
        {13913, 120},
    }
    _pcsp__b64encode = [][2]uint32{
        {1, 0},
        {4, 8},
        {6, 16},
        {8, 24},
        {10, 32},
        {831, 40},
        {832, 32},
        {834, 24},
        {836, 16},
        {838, 8},
        {843, 0},
    }
)

var funcs = []loader.CFunc{
    {"__native_entry__", 0, 67, 0, nil},
    {"_b64decode", _entry__b64decode, _size__b64decode, _stack__b64decode, _pcsp__b64decode},
    {"_b64encode", _entry__b64encode, _size__b64encode, _stack__b64encode, _pcsp__b64encode},
}
